{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- $persistenceAnnotations := .Values.persistence.annotations }}
{{- if .Values.persistence.skipuninstall }}
{{- $persistenceAnnotations = merge $persistenceAnnotations (dict "helm.sh/resource-policy" "keep") }}
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "Mikochi.fullname" . }}
  labels:
{{ include "Mikochi.labels" . | indent 4 }}
  {{- with $persistenceAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end -}}
